In [23]:
# from IPython import parallel
# rc = parallel.Client()
# dv = rc[:]
# rc.ids

[0, 1, 2, 3]

In [1]:
#%%px --local 
import os
import sys
sys.path.append(os.environ['HOME']+'/home/proj/stats/MCMC')
os.environ['PYTHONPATH'] = os.environ['HOME']+'/home/proj/stats/MCMC'

import csv

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

#%matplotlib inline
import model
import driver
import data

min Temp = 3.000000 K; max Temp = 100.000000 K
python version of blackbody


In [4]:
### read the file of fluxes and errors
### could make a numpy record array instead of separate ones for name, z, err, flux?
### nb. this version has the same length for each row

herus_file = "herus_phot.csv"
herus_file = "herus_phot_csv.csv"


speed_of_light = 299792.458 ### micron GHz

def toFloat(s):
    return np.float(s) if s!='' else np.nan

names = []
zarr = []
fluxes = []
errs = []
with open(herus_file, "rb") as csvfile:
    hreader = csv.reader(csvfile)
    headers = hreader.next()
    ncol = len(headers)
    name_column = headers=='Name'
    z_column = headers=='Redshift'
    flux_columns = [i for i in range(ncol) if headers[i].startswith('F')]
    err_columns = [i for i in range(ncol) if headers[i].startswith('E')]
    lambdas = speed_of_light/np.array([float(headers[i].split('_')[0][1:]) for i in flux_columns])  ### lambda in um
    lambdas_err = speed_of_light/np.array([float(headers[i].split('_')[0][1:]) for i in flux_columns])
    assert(np.all(lambdas==lambdas_err))   ### check correct order
    
    for row in hreader:
        names.append(row[name_column])
        zarr.append(row[z_column])
        fluxes.append([toFloat(row[c]) for c in flux_columns])
        errs.append([toFloat(row[c]) for c in err_columns])


In [32]:
### read the file of fluxes and errors
### could make a numpy record array instead of separate ones for name, z, err, flux?
### nb. this version deletes nonexistent entries, but puts err=np.nan if there is a flux but no entry
#### used in driver.py: readfluxes_DLC_2014
import re
Epat = r'^E\d+_'
Fpat = r'^F\d+_'
UL25 = True
fluxes = []
errs = []
names = []
zarr = []
with open(herus_file, "rb") as csvfile:
    hreader = csv.reader(csvfile)
    headers = np.array(hreader.next())
    ncol = len(headers)
    name_column = np.where(headers=='Name')[0][0]
    z_column = np.where(headers=='Redshift')[0][0]
    flux_columns = np.array([i for i in range(ncol) if re.match(Fpat, headers[i])])
    err_columns = np.array([i for i in range(ncol) if re.match(Epat, headers[i])])
    assert np.all(err_columns == flux_columns+1)

    lambda_obs = np.array([float(headers[i].split('_')[0][1:]) for i in flux_columns])  ### Freq in GHz
    lambda_err = np.array([float(headers[i].split('_')[0][1:]) for i in flux_columns])
    assert(np.all(lambda_obs==lambda_err))   ### check correct order
    
    for row in hreader:
        row = np.asarray(row)
        if np.all(row==''): continue  ## ignore blank lines
        z = np.float(row[z_column])
        dat = zip(row[flux_columns], row[err_columns], lambda_obs)
        dat_compressed = np.array([[np.float(f), toFloat(e), l] for f,e,l in dat if f!=''])
        #flux = np.array([np.float(c) for c in row[flux_columns] if c!=''])
        #err = np.array([np.float(c) for c in row[err_columns] if c!=''])
        flux = np.array(dat_compressed[:,0])
        sig = np.array(dat_compressed[:,1])
        lambda_obs_1 = np.array(dat_compressed[:,2])
        
        nu_obs = speed_of_light/lambda_obs_1
        if UL25:
            l25 = np.where(np.round(lambda_obs_1)==25)[0]
            if l25:
                sig[l25] = flux[l25]
                flux[l25] = 0

        nu_rest = nu_obs*(1+z)

        names.append(row[name_column])
        zarr.append(z)
        fluxes.append(flux)
        errs.append(sig)

elens = [len(e) for e in errs]


In [33]:
reload(data)
d = data.readfluxes_DLC_2014(filename=herus_file)
d1 = d[1]
print [di.name for di in d]
print d[-3].name, d[-3].d, d[-3].z
print d[-1].name, d[-1].d, d[-1].z

['IRAS00188-0856', 'IRAS00397-1312', 'IRAS01003-2238', 'IRAS03158+4227', 'IRAS03521+0028', 'IRAS05189-2524', 'IRAS06035-7102', 'IRAS06206-6315', 'IRAS07598+6508', 'IRAS08311-2459', 'IRAS08572+3915', 'IRAS09022-3615', 'IRAS10378+1109', 'IRAS10565+2448', 'IRAS11095-0238', 'IRAS12071-0444', 'IRAS13120-5453', 'IRAS13451+1232', 'IRAS14348-1447', 'IRAS14378-3651', 'IRAS15250+3609', 'IRAS15462-0450', 'IRAS16090-0139', 'IRAS17208-0014', 'IRAS19254-7245', 'IRAS19297-0406', 'IRAS20087-0308', 'IRAS20100-4156', 'IRAS20414-1651', 'IRAS20551-4250', 'IRAS22491-1808', 'IRAS23128-5919', 'IRAS23230-6926', 'IRAS23253-5415', 'IRAS23365+3604', 'Mrk1014', 'UGC5101', '3C273', 'Mrk231', 'Mrk273', 'Mrk463', 'Arp220-short', 'NGC6240', 'Arp220']
Arp220-short [  85.64651107   76.28        123.71         30.4137       12.0643
    4.1448      103.8         112.4           0.832         6.286     ] 0.018
Arp220 [  30.1     11.7      3.9      2.2      4.3      7.6     12.2     18.4
   24.4     32.2     39.7     50.9 

In [2]:
#%matplotlib osx
%run driver.py --format=DLC_2014 --fdir=./figs_DLC_2014_2 --odir=./out_DLC_2014_2 --file=./herus_phot.csv 0 1 2 3

/Volumes/Data/Users/jaffe/Library/Python/2.7/lib/python/site-packages/matplotlib-1.3.1-py2.7-macosx-10.6-intel.egg/matplotlib/__init__.py:1155: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


normal behaviour
filename: ./herus_phot.csv
fig dir: ./figs_DLC_2014_2/
out dir: ./out_DLC_2014_2/
data range None
DLC_UL = 1
format = 0
filetype = DLC_2014
which= [3, 2, 1, 0]
Using file ./herus_phot.csv
keywords: {'random': True, 'randomrestart': True, 'filetype': 'DLC_2014', 'format': 0, 'DLC_ul': True}
Two-Component beta = 2
Object[s] IRAS00188-0856(z=0.128)
done with chain 0. naccept=9368 (0.624492)

100% |########################################################################|
100% |########################################################################|



per block:  [2481 2501 1864    4 2501   22]
done with chain 1. naccept=207779 (0.692594)
per block:  [50000 50001 40800  2573 50001 14409]
chi2 at max = 23.959789
Max ln likelihood -11.979895 at parameters:
[ -4.06286082e+04   2.00000000e+00   5.07408935e+00   1.19166173e-01
   2.00000000e+00   3.16992381e+01]
            \log A_1 mean = -34964.4 +- 15704.2
                 T_1 mean = 17.1866 +- 8.25366
            \log A_2 mean = 0.121946 +- 0.0226082
                 T_2 mean = 31.6239 +- 0.682885
ln Pr of mean = -12.010634
chi2(mean) = 24.021268
Object[s] IRAS00397-1312(z=0.262)

100% |########################################################################|



done with chain 0. naccept=9182 (0.612093)

100% |########################################################################|
100% |########################################################################|



per block:  [2459 2501 1688    6 2501   32]
done with chain 1. naccept=218466 (0.728218)
per block:  [49756 50001 43959  3424 50001 21330]
chi2 at max = 11.765224
Max ln likelihood -5.882612 at parameters:
[ -1.23900439e+03   2.00000000e+00   3.94575390e+01  -6.49895809e-01
   2.00000000e+00   4.21538594e+01]
            \log A_1 mean = -1683.74 +- 1334.84
                 T_1 mean = 22.3547 +- 11.3728
            \log A_2 mean = -0.639995 +- 0.0676094
                 T_2 mean = 41.829 +- 2.18748
ln Pr of mean = -6.278784
chi2(mean) = 12.557568
Object[s] IRAS01003-2238(z=0.118)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=8895 (0.592960)

100% |########################################################################|
100% |########################################################################|
model.py:418: RuntimeWarning: overflow encountered in double_scalars
  self.A1 = 10.0**logA1



per block:  [2487 2501 1357    9 2501   45]
done with chain 1. naccept=238061 (0.793534)
per block:  [49984 50001 46484 12807 50001 28789]
chi2 at max = 2.769111
Max ln likelihood -1.384555 at parameters:
[ -1.56484819e+04   2.00000000e+00   6.79910227e+00  -7.85932688e-01
   2.00000000e+00   4.47821119e+01]
            \log A_1 mean = -30302.9 +- 15069.3
                 T_1 mean = 23.8868 +- 12.1868
            \log A_2 mean = -0.778126 +- 0.0855283
                 T_2 mean = 44.5541 +- 2.53135
ln Pr of mean = -1.545912
chi2(mean) = 3.091823
Object[s] IRAS03158+4227(z=0.134)

100% |########################################################################|



Number of prior resamples: 4
done with chain 0. naccept=9226 (0.615026)

100% |########################################################################|
100% |########################################################################|



per block:  [2426 2501 1782    4 2501   17]
done with chain 1. naccept=203696 (0.678984)
per block:  [49913 50001 40892  1212 50001 11682]
chi2 at max = 59.010939
Max ln likelihood -29.505469 at parameters:
[  2.37107799   2.           4.00573161   0.22847934   2.          29.5947392 ]
            \log A_1 mean = -3554.93 +- 1978.08
                 T_1 mean = 16.639 +- 7.8928
            \log A_2 mean = 0.206497 +- 0.0526162
                 T_2 mean = 30.2551 +- 1.42593
ln Pr of mean = -32.363925
chi2(mean) = 64.727850
Object[s] IRAS03521+0028(z=0.152)

100% |########################################################################|



done with chain 0. naccept=6114 (0.407573)

100% |########################################################################|
100% |########################################################################|



per block:  [ 520 2501  538   10 2501   49]
done with chain 1. naccept=109709 (0.365695)
per block:  [  150 50001  2012  2356 50001  5194]
chi2 at max = 0.048680
Max ln likelihood -0.024340 at parameters:
[  0.45554599   2.          11.48875304  -0.22073338   2.          37.94324776]
            \log A_1 mean = 0.837742 +- 1.78488
                 T_1 mean = 9.33573 +- 2.56505
            \log A_2 mean = -0.192058 +- 0.0343816
                 T_2 mean = 37.3166 +- 0.89349
ln Pr of mean = -3.619827
chi2(mean) = 7.239653
Object[s] IRAS05189-2524(z=0.043)

100% |########################################################################|



Number of prior resamples: 424
done with chain 0. naccept=7208 (0.480501)


100% |########################################################################|



per block:  [  13 2501   22 1125 2501 1051]
done with chain 1. naccept=101006 (0.336686)
per block:  [   89 50001   336   153 50001   431]
chi2 at max = 175.558362
Max ln likelihood -87.779181 at parameters:
[  0.45909783   2.          34.5180921   -1.81296539   2.          99.99246169]
            \log A_1 mean = 0.458425 +- 0.0550784
                 T_1 mean = 34.5948 +- 1.08098
            \log A_2 mean = -2.41368 +- 11.9224
                 T_2 mean = 99.6781 +- 2.51256
ln Pr of mean = -9186.404079
chi2(mean) = 18372.808157
Object[s] IRAS06035-7102(z=0.079)

100% |########################################################################|



done with chain 0. naccept=5123 (0.341511)

100% |########################################################################|
100% |########################################################################|



per block:  [   7 2501   36   24 2501   59]
done with chain 1. naccept=107878 (0.359592)
per block:  [  676 50001  1519   576 50001  5110]
chi2 at max = 43.909930
Max ln likelihood -21.954965 at parameters:
[  0.1942254    2.          33.11739095  -1.43970346   2.          60.29891836]
            \log A_1 mean = 0.188489 +- 0.0113324
                 T_1 mean = 33.2431 +- 0.393601
            \log A_2 mean = -1.38337 +- 0.0954063
                 T_2 mean = 58.4024 +- 3.33778
ln Pr of mean = -22.253397
chi2(mean) = 44.506794
Object[s] IRAS06206-6315(z=0.092)

100% |########################################################################|



Number of prior resamples: 3
done with chain 0. naccept=8325 (0.554963)

100% |########################################################################|
100% |########################################################################|



per block:  [2441 2501  823   26 2501   38]
Number of prior resamples: 3
done with chain 1. naccept=197263 (0.657541)
per block:  [49863 50001 45936   242 50001  1225]
chi2 at max = 101.607974
Max ln likelihood -50.803987 at parameters:
[ -1.17802230e+04   2.00000000e+00   1.78635667e+01   2.57409837e-01
   2.00000000e+00   3.34608583e+01]
            \log A_1 mean = -4133.2 +- 3318.24
                 T_1 mean = 15.2608 +- 7.7978
            \log A_2 mean = 0.496453 +- 0.272831
                 T_2 mean = 27.6542 +- 5.66637
ln Pr of mean = -947.559778
chi2(mean) = 1895.119557
Object[s] IRAS07598+6508(z=0.148)

100% |########################################################################|



done with chain 0. naccept=5471 (0.364709)

100% |########################################################################|
100% |########################################################################|



per block:  [  14 2501   36   13 2501  411]
done with chain 1. naccept=127726 (0.425752)
per block:  [  958 50001  7720  9803 50001  9248]
chi2 at max = 2.165250
Max ln likelihood -1.082625 at parameters:
[ -0.07622128   2.          28.65600694  -1.86019694   2.          65.85815035]
            \log A_1 mean = -0.0807242 +- 0.0493463
                 T_1 mean = 26.8921 +- 1.73901
            \log A_2 mean = -1.37626 +- 0.467616
                 T_2 mean = 55.0866 +- 11.5278
ln Pr of mean = -27.550324
chi2(mean) = 55.100649
Object[s] IRAS08311-2459(z=0.100)

100% |########################################################################|



Number of prior resamples: 3
done with chain 0. naccept=5406 (0.360376)


100% |########################################################################|



per block:  [ 145 2501  149    8 2501  107]
done with chain 1. naccept=104524 (0.348412)
per block:  [  217 50001  2543   931 50001   836]
chi2 at max = 7.194810
Max ln likelihood -3.597405 at parameters:
[  0.10673077   2.          16.02562844   0.13332427   2.          36.18519014]
            \log A_1 mean = 0.118434 +- 0.681608
                 T_1 mean = 15.3465 +- 2.7766
            \log A_2 mean = 0.13889 +- 0.0299805
                 T_2 mean = 36.215 +- 0.98799
ln Pr of mean = -3.921690
chi2(mean) = 7.843380
Object[s] IRAS08572+3915(z=0.058)

100% |########################################################################|



done with chain 0. naccept=9613 (0.640824)

100% |########################################################################|
100% |########################################################################|



per block:  [2436 2501 2122   13 2501   45]
done with chain 1. naccept=192305 (0.641015)
per block:  [49998 50001 39863  1083 50001  1364]
chi2 at max = 21.451469
Max ln likelihood -10.725735 at parameters:
[ -4.44300515e+03   2.00000000e+00   2.85528320e+01  -3.81975085e-01
   2.00000000e+00   4.64408198e+01]
            \log A_1 mean = -4081.88 +- 1741.03
                 T_1 mean = 24.6853 +- 12.5491
            \log A_2 mean = -0.38036 +- 0.00782476
                 T_2 mean = 46.4055 +- 0.167568
ln Pr of mean = -10.789686
chi2(mean) = 21.579371
Object[s] IRAS09022-3615(z=0.060)

100% |########################################################################|



done with chain 0. naccept=9039 (0.602560)

100% |########################################################################|
100% |########################################################################|



per block:  [2469 2501 1536   13 2501   24]
Number of prior resamples: 8
done with chain 1. naccept=198370 (0.661231)
per block:  [49874 50001 44558  1294 50001  2647]
chi2 at max = 210.981112
Max ln likelihood -105.490556 at parameters:
[ -3.65421462   2.          31.53387442   0.51069118   2.          35.99613062]
            \log A_1 mean = -4980.63 +- 2973.57
                 T_1 mean = 19.3348 +- 9.51802
            \log A_2 mean = 0.511288 +- 0.0148185
                 T_2 mean = 35.9788 +- 0.438568
ln Pr of mean = -105.585687
chi2(mean) = 211.171373
Object[s] IRAS10378+1109(z=0.136)

100% |########################################################################|



done with chain 0. naccept=5146 (0.343044)

100% |########################################################################|
100% |########################################################################|



per block:  [  19 2501   27    5 2501   98]
done with chain 1. naccept=146149 (0.487162)
per block:  [ 4707 50001 16944  9124 50001 15377]
chi2 at max = 25.871722
Max ln likelihood -12.935861 at parameters:
[ -0.14619246   2.          29.67650546  -1.5957861    2.          61.06087312]
            \log A_1 mean = -0.168571 +- 0.0665701
                 T_1 mean = 28.894 +- 2.05608
            \log A_2 mean = -1.40597 +- 0.367867
                 T_2 mean = 56.9678 +- 8.08352
ln Pr of mean = -34.131969
chi2(mean) = 68.263938
Object[s] IRAS10565+2448(z=0.043)

100% |########################################################################|



done with chain 0. naccept=9447 (0.629758)

100% |########################################################################|
100% |########################################################################|



per block:  [2498 2501 1927   10 2501   15]
done with chain 1. naccept=103485 (0.344949)
per block:  [  150 50001  1377   231 50001  1730]
chi2 at max = 939.825795
Max ln likelihood -469.912898 at parameters:
[  0.40345568   2.          21.87610791   0.67771165   2.          34.07627479]
            \log A_1 mean = -0.597808 +- 18.6498
                 T_1 mean = 20.8818 +- 0.893244
            \log A_2 mean = 0.713918 +- 0.0276301
                 T_2 mean = 33.7103 +- 0.283023
ln Pr of mean = -1671.755738
chi2(mean) = 3343.511477
Object[s] IRAS11095-0238(z=0.107)

100% |########################################################################|



done with chain 0. naccept=5213 (0.347510)

100% |########################################################################|
100% |########################################################################|



per block:  [  14 2501   35    9 2501  158]
done with chain 1. naccept=212353 (0.707841)
per block:  [ 3950 50001 18408 47529 50001 42469]
chi2 at max = 10.845094
Max ln likelihood -5.422547 at parameters:
[ -0.49472297   2.          41.0588298   -1.97631806   2.          59.12490391]
            \log A_1 mean = -0.492602 +- 0.0564255
                 T_1 mean = 41.8702 +- 2.89002
            \log A_2 mean = -7.53501 +- 3.45186
                 T_2 mean = 69.4179 +- 16.766
ln Pr of mean = -8.815520
chi2(mean) = 17.631040
Object[s] IRAS12071-0444(z=0.128)

100% |########################################################################|



done with chain 0. naccept=8884 (0.592227)

100% |########################################################################|
100% |########################################################################|



per block:  [2061 2501 1772   10 2501   44]
done with chain 1. naccept=201766 (0.672551)
per block:  [49948 50001 38810  1919 50001 11092]
chi2 at max = 7.326850
Max ln likelihood -3.663425 at parameters:
[ -4.52198880e+03   2.00000000e+00   1.61996909e+01  -3.45844164e-01
   2.00000000e+00   3.86923781e+01]
            \log A_1 mean = -4489.7 +- 1911.72
                 T_1 mean = 20.79 +- 10.3395
            \log A_2 mean = -0.346029 +- 0.0128039
                 T_2 mean = 38.6998 +- 0.511641
ln Pr of mean = -3.663615
chi2(mean) = 7.327230
Object[s] IRAS13120-5453(z=0.031)

100% |########################################################################|



done with chain 0. naccept=5085 (0.338977)

100% |########################################################################|
100% |########################################################################|



per block:  [  18 2501   60    3 2501    7]
done with chain 1. naccept=125205 (0.417349)
per block:  [  557 50001  1132 21553 50001  1966]
chi2 at max = 261.677548
Max ln likelihood -130.838774 at parameters:
[  1.40564832   2.          25.17279684   0.67046495   2.          40.14483007]
            \log A_1 mean = 1.37882 +- 0.0336461
                 T_1 mean = 23.5577 +- 1.68812
            \log A_2 mean = 0.837664 +- 0.130977
                 T_2 mean = 38.1629 +- 1.51198
ln Pr of mean = -263.202435
chi2(mean) = 526.404869
Object[s] IRAS13451+1232(z=0.122)

100% |########################################################################|



Number of prior resamples: 138
done with chain 0. naccept=6190 (0.412639)

100% |########################################################################|
100% |########################################################################|



per block:  [ 389 2501  491  108 2501  205]
done with chain 1. naccept=103229 (0.344096)
per block:  [  150 50001  2015    62 50001  1005]
chi2 at max = 577.190874
Max ln likelihood -288.595437 at parameters:
[  0.20366068   2.          18.46640572  -0.18801467   2.          27.6013031 ]
            \log A_1 mean = -0.572011 +- 7.74447
                 T_1 mean = 25.3103 +- 7.08283
            \log A_2 mean = -0.26643 +- 0.135759
                 T_2 mean = 31.7426 +- 4.9653
ln Pr of mean = -585.334481
chi2(mean) = 1170.668962
Object[s] IRAS14348-1447(z=0.083)

100% |########################################################################|



Number of prior resamples: 4
done with chain 0. naccept=5700 (0.379975)

100% |########################################################################|
100% |########################################################################|



per block:  [  21 2501   32  323 2501  327]
done with chain 1. naccept=101094 (0.336979)
per block:  [   93 50001   614    23 50001   367]
chi2 at max = 105299.728405
Max ln likelihood -52649.864202 at parameters:
[  4.48881609e-02   2.00000000e+00   5.69602743e+01  -6.81675534e-01
   2.00000000e+00   5.77472951e+01]
            \log A_1 mean = 0.0685836 +- 0.0983617
                 T_1 mean = 55.2673 +- 4.29025
            \log A_2 mean = -0.694745 +- 0.806532
                 T_2 mean = 61.6869 +- 6.14902
ln Pr of mean = -53491.252530
chi2(mean) = 106982.505060
Object[s] IRAS14378-3651(z=0.068)

100% |########################################################################|



done with chain 0. naccept=8416 (0.561029)

100% |########################################################################|
100% |########################################################################|



per block:  [2472 2501  894   23 2501   30]
done with chain 1. naccept=131637 (0.438789)
per block:  [ 8715 50001 21700   293 50001   932]
chi2 at max = 8.911109
Max ln likelihood -4.455555 at parameters:
[ -0.5059482    2.          21.49544209   0.19626921   2.          36.98390908]
            \log A_1 mean = -407.173 +- 1067.27
                 T_1 mean = 23.0474 +- 6.90754
            \log A_2 mean = 0.268062 +- 0.265313
                 T_2 mean = 35.6335 +- 4.88189
ln Pr of mean = -180.662275
chi2(mean) = 361.324550
Object[s] IRAS15250+3609(z=0.055)

100% |########################################################################|



Number of prior resamples: 8
done with chain 0. naccept=9109 (0.607226)

100% |########################################################################|
100% |########################################################################|



per block:  [2474 2501 1606    9 2501   23]
Number of prior resamples: 2
done with chain 1. naccept=205564 (0.685211)
per block:  [49988 50001 41919   269 50001 13391]
chi2 at max = 172.888657
Max ln likelihood -86.444328 at parameters:
[ -2.11604185e+03   2.00000000e+00   1.96065643e+01   1.18009118e-01
   2.00000000e+00   3.62248884e+01]
            \log A_1 mean = -7690.06 +- 4350.7
                 T_1 mean = 16.597 +- 8.39503
            \log A_2 mean = 0.304988 +- 0.168904
                 T_2 mean = 30.3566 +- 4.74317
ln Pr of mean = -243.503913
chi2(mean) = 487.007826
Object[s] IRAS15462-0450(z=0.100)

100% |########################################################################|



done with chain 0. naccept=5466 (0.364376)

100% |########################################################################|
100% |########################################################################|



per block:  [   6 2501   56   19 2501  388]
done with chain 1. naccept=207558 (0.691858)
per block:  [ 2779 50001 10379 47984 50001 46419]
chi2 at max = 11.799803
Max ln likelihood -5.899902 at parameters:
[ -0.25611357   2.          36.99361573 -21.72513193   2.          62.61456843]
            \log A_1 mean = -0.249758 +- 0.0269641
                 T_1 mean = 36.6372 +- 1.35143
            \log A_2 mean = -11.7093 +- 6.35261
                 T_2 mean = 65.7437 +- 18.2686
ln Pr of mean = -6.324837
chi2(mean) = 12.649674
Object[s] IRAS16090-0139(z=0.134)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=9096 (0.606360)

100% |########################################################################|
100% |########################################################################|



per block:  [2476 2501 1600    5 2501   18]
Number of prior resamples: 2
done with chain 1. naccept=225727 (0.752421)
per block:  [49950 50001 43890  1699 50001 30191]
chi2 at max = 29.505691
Max ln likelihood -14.752845 at parameters:
[ -3.90161152e+03   2.00000000e+00   1.40424592e+01   8.67435106e-02
   2.00000000e+00   3.55137568e+01]
            \log A_1 mean = -3667.68 +- 2980.34
                 T_1 mean = 19.1281 +- 9.24615
            \log A_2 mean = 0.103268 +- 0.0723312
                 T_2 mean = 35.0256 +- 2.048
ln Pr of mean = -18.608639
chi2(mean) = 37.217278
Object[s] IRAS17208-0014(z=0.043)

100% |########################################################################|



Number of prior resamples: 4
done with chain 0. naccept=9473 (0.631491)

100% |########################################################################|
100% |########################################################################|



per block:  [2468 2501 1965   12 2501   31]
done with chain 1. naccept=102509 (0.341696)
per block:  [  118 50001  1352   403 50001   639]
chi2 at max = 207.131057
Max ln likelihood -103.565528 at parameters:
[  0.98845593   2.          18.8321905    0.98065605   2.          35.4900418 ]
            \log A_1 mean = 0.70813 +- 4.03551
                 T_1 mean = 17.4023 +- 1.33025
            \log A_2 mean = 1.02565 +- 0.0371269
                 T_2 mean = 34.9818 +- 0.414912
ln Pr of mean = -362.331233
chi2(mean) = 724.662466
Object[s] IRAS19254-7245(z=0.062)

100% |########################################################################|



done with chain 0. naccept=5049 (0.336578)

100% |########################################################################|
100% |########################################################################|



per block:  [  10 2501   20    3 2501   19]
done with chain 1. naccept=150445 (0.501482)
per block:  [ 3880 50001  7664 34407 50001  4497]
chi2 at max = 147.719311
Max ln likelihood -73.859656 at parameters:
[  0.55664981   2.          25.83585934  -0.65591168   2.          47.46205242]
            \log A_1 mean = 0.525961 +- 0.0394333
                 T_1 mean = 23.4155 +- 1.37148
            \log A_2 mean = -0.192578 +- 0.17984
                 T_2 mean = 40.4 +- 2.5257
ln Pr of mean = -107.754670
chi2(mean) = 215.509341
Object[s] IRAS19297-0406(z=0.086)

100% |########################################################################|



done with chain 0. naccept=8961 (0.597360)

100% |########################################################################|
100% |########################################################################|



per block:  [2378 2501 1562    4 2501   20]
Number of prior resamples: 2
done with chain 1. naccept=203854 (0.679511)
per block:  [49825 50001 43653  5514 50001  4865]
chi2 at max = 75.202899
Max ln likelihood -37.601449 at parameters:
[ -1.80380442e+03   2.00000000e+00   3.30148783e+01   4.44889648e-01
   2.00000000e+00   3.46297507e+01]
            \log A_1 mean = -5270.51 +- 5743.12
                 T_1 mean = 18.8222 +- 9.0707
            \log A_2 mean = 0.447365 +- 0.0309059
                 T_2 mean = 34.5595 +- 0.84837
ln Pr of mean = -37.978187
chi2(mean) = 75.956374
Object[s] IRAS20087-0308(z=0.106)

100% |########################################################################|



Number of prior resamples: 16
done with chain 0. naccept=9389 (0.625892)


100% |########################################################################|



per block:  [2457 2501 1896   14 2501   25]
done with chain 1. naccept=194664 (0.648878)
per block:  [49819 50001 38223    55 50001  6570]
chi2 at max = 60.766060
Max ln likelihood -30.383030 at parameters:
[ -1.65419913e+04   2.00000000e+00   1.92651144e+01   4.95672764e-01
   2.00000000e+00   3.04044824e+01]
            \log A_1 mean = -8998.76 +- 6399.67
                 T_1 mean = 16.4363 +- 7.70303
            \log A_2 mean = 0.523624 +- 0.0299864
                 T_2 mean = 29.5783 +- 0.661065
ln Pr of mean = -47.504999
chi2(mean) = 95.009998
Object[s] IRAS20100-4156(z=0.130)

100% |########################################################################|



done with chain 0. naccept=9500 (0.633291)

100% |########################################################################|
100% |########################################################################|



per block:  [2459 2501 1985   16 2501   43]
done with chain 1. naccept=191248 (0.637491)
per block:  [49719 50001 40400   627 50001   505]
chi2 at max = 16.316456
Max ln likelihood -8.158228 at parameters:
[ -1.26830473e+00   2.00000000e+00   1.68695581e+01  -2.94152666e-02
   2.00000000e+00   3.90390804e+01]
            \log A_1 mean = -3148.66 +- 2147.63
                 T_1 mean = 21.1435 +- 10.3647
            \log A_2 mean = -0.0253059 +- 0.00351623
                 T_2 mean = 38.9673 +- 0.105504
ln Pr of mean = -8.248770
chi2(mean) = 16.497540
Object[s] IRAS20414-1651(z=0.871)

100% |########################################################################|



done with chain 0. naccept=9262 (0.617426)

100% |########################################################################|
100% |########################################################################|



per block:  [2494 2501 1728   18 2501   25]
done with chain 1. naccept=198106 (0.660351)
per block:  [49933 50001 44771   541 50001  2864]
chi2 at max = 105.363386
Max ln likelihood -52.681693 at parameters:
[ -1.055681     2.          12.82919268  -0.79921211   2.          52.39865244]
            \log A_1 mean = -2685.07 +- 1608.03
                 T_1 mean = 25.3462 +- 13.3918
            \log A_2 mean = -0.703928 +- 0.159232
                 T_2 mean = 48.4883 +- 5.82435
ln Pr of mean = -149.966548
chi2(mean) = 299.933097
Object[s] IRAS20551-4250(z=0.043)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=5054 (0.336911)

100% |########################################################################|
100% |########################################################################|



per block:  [   8 2501   29    4 2501   16]
done with chain 1. naccept=116548 (0.388492)
per block:  [ 4012 50001  5805  2146 50001  4588]
chi2 at max = 424.674963
Max ln likelihood -212.337481 at parameters:
[  0.40614528   2.          29.10806703  -0.48214598   2.          51.96726368]
            \log A_1 mean = 0.405801 +- 0.0144001
                 T_1 mean = 28.4973 +- 0.54195
            \log A_2 mean = -0.413484 +- 0.0377683
                 T_2 mean = 50.6181 +- 0.716624
ln Pr of mean = -212.537148
chi2(mean) = 425.074296
Object[s] IRAS22491-1808(z=0.078)

100% |########################################################################|



done with chain 0. naccept=5139 (0.342577)

100% |########################################################################|
100% |########################################################################|



per block:  [  35 2501   60   11 2501   36]
done with chain 1. naccept=106084 (0.353612)
per block:  [  208 50001  1997  1523 50001  2359]
chi2 at max = 28.374932
Max ln likelihood -14.187466 at parameters:
[  0.15340189   2.          25.94853027  -0.61463526   2.          48.29066431]
            \log A_1 mean = 0.101072 +- 0.120876
                 T_1 mean = 24.3963 +- 1.59156
            \log A_2 mean = -0.450848 +- 0.144719
                 T_2 mean = 45.4093 +- 2.44588
ln Pr of mean = -49.506804
chi2(mean) = 99.013608
Object[s] IRAS23128-5919(z=0.045)

100% |########################################################################|



done with chain 0. naccept=6820 (0.454636)

100% |########################################################################|
100% |########################################################################|



per block:  [  15 2501   34  906 2501  868]
Number of prior resamples: 41
done with chain 1. naccept=185241 (0.617468)
per block:  [  508 50001   917 49859 50001 33960]
chi2 at max = 254.687263
Max ln likelihood -127.343632 at parameters:
[  0.28271339   2.          38.36152415  -3.48956901   2.          86.76931047]
            \log A_1 mean = 0.28393 +- 0.0135898
                 T_1 mean = 38.3492 +- 0.316906
            \log A_2 mean = -3889.86 +- 2723.58
                 T_2 mean = 69.2602 +- 17.8257
ln Pr of mean = -128.361705
chi2(mean) = 256.723410
Object[s] IRAS23230-6926(z=0.107)

100% |########################################################################|



Number of prior resamples: 38
done with chain 0. naccept=9699 (0.646557)

100% |########################################################################|
100% |########################################################################|



per block:  [2501 2501 2041   67 2501   93]
done with chain 1. naccept=191585 (0.638615)
per block:  [49840 50001 37735    59 50001  3954]
chi2 at max = 33.277123
Max ln likelihood -16.638562 at parameters:
[ -5.55566765e+02   2.00000000e+00   6.61846686e+00  -2.16359589e-01
   2.00000000e+00   3.91438490e+01]
            \log A_1 mean = -5404.33 +- 3937.17
                 T_1 mean = 20.296 +- 10.0823
            \log A_2 mean = -0.169358 +- 0.0790712
                 T_2 mean = 37.4139 +- 2.74772
ln Pr of mean = -31.812326
chi2(mean) = 63.624652
Object[s] IRAS23253-5415(z=0.130)

100% |########################################################################|



done with chain 0. naccept=5463 (0.364176)

100% |########################################################################|
100% |########################################################################|



per block:  [   8 2501   19   42 2501  397]
done with chain 1. naccept=113350 (0.377832)
per block:  [ 1550 50001  8604   984 50001  2215]
chi2 at max = 12.252181
Max ln likelihood -6.126090 at parameters:
[  0.43038097   2.          22.67267284  -0.61408345   2.          42.1194002 ]
            \log A_1 mean = 0.447384 +- 0.0640874
                 T_1 mean = 22.9335 +- 0.976925
            \log A_2 mean = -0.748786 +- 0.105021
                 T_2 mean = 44.4874 +- 2.3606
ln Pr of mean = -7.243153
chi2(mean) = 14.486307
Object[s] IRAS23365+3604(z=0.065)

100% |########################################################################|



Number of prior resamples: 15
done with chain 0. naccept=5218 (0.347843)

100% |########################################################################|
100% |########################################################################|



per block:  [  80 2501   96    8 2501   37]
Number of prior resamples: 1164
done with chain 1. naccept=106860 (0.356199)
per block:  [  263 50001  4497  1142 50001   961]
chi2 at max = 48.802233
Max ln likelihood -24.401117 at parameters:
[  0.1062557    2.          23.38830387   0.29203514   2.          36.25434857]
            \log A_1 mean = 0.165457 +- 1.30917
                 T_1 mean = 19.5117 +- 4.0055
            \log A_2 mean = 0.337666 +- 0.049222
                 T_2 mean = 35.776 +- 0.784564
ln Pr of mean = -29.973874
chi2(mean) = 59.947748
Object[s] Mrk1014(z=0.163)

100% |########################################################################|



Number of prior resamples: 5
done with chain 0. naccept=5352 (0.356776)

100% |########################################################################|
100% |########################################################################|



per block:  [ 116 2501  168    6 2501   65]
done with chain 1. naccept=121948 (0.406492)
per block:  [ 5004 50001  7947  2505 50001  6495]
chi2 at max = 3.979195
Max ln likelihood -1.989597 at parameters:
[ -0.15293318   2.          24.22679771  -0.91796972   2.          47.73914064]
            \log A_1 mean = -12.597 +- 44.95
                 T_1 mean = 20.8746 +- 5.12532
            \log A_2 mean = -0.73963 +- 0.193718
                 T_2 mean = 44.8545 +- 3.17724
ln Pr of mean = -1377.431678
chi2(mean) = 2754.863356
Object[s] UGC5101(z=0.039)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=9336 (0.622359)

100% |########################################################################|
100% |########################################################################|
/Volumes/Data/Users/jaffe/home/proj/stats/MCMC/GaussianData.py:47: RuntimeWarning: overflow encountered in true_divide
  return dot(A.transpose()/self.sig2,A)



per block:  [2446 2501 1862    9 2501   22]
done with chain 1. naccept=180400 (0.601331)
per block:  [43934 50001 34574  1024 50001   871]
chi2 at max = 805.956387
Max ln likelihood -402.978193 at parameters:
[  0.76984893   2.          19.15168392   0.99020014   2.          30.83744374]
            \log A_1 mean = -8541.56 +- 4608.97
                 T_1 mean = 16.8973 +- 7.35826
            \log A_2 mean = 1.0766 +- 0.0178095
                 T_2 mean = 30.0856 +- 0.154921
ln Pr of mean = -758.394262
chi2(mean) = 1516.788525
Object[s] 3C273(z=0.158)


done with chain 0. naccept=9756 (0.650357)

100% |########################################################################|
100% |########################################################################|



per block:  [2493 2501 2227    9 2501   30]
done with chain 1. naccept=189208 (0.630691)
per block:  [49820 50001 39110   116 50001   165]
chi2 at max = 250761095.562480
Max ln likelihood -125380547.781240 at parameters:
[ -1.28270555e+04   2.00000000e+00   5.45574491e+01   6.92923951e-01
   2.00000000e+00   5.99698595e+01]
            \log A_1 mean = -6075.86 +- 4382.46
                 T_1 mean = 31.4147 +- 16.5001
            \log A_2 mean = 0.692736 +- 0.00524077
                 T_2 mean = 59.9729 +- 0.0746581
ln Pr of mean = -125380548.666643
chi2(mean) = 250761097.333285
Object[s] Mrk231(z=0.042)

100% |########################################################################|



Number of prior resamples: 9
done with chain 0. naccept=5358 (0.357176)

100% |########################################################################|
100% |########################################################################|



per block:  [  54 2501   93   82 2501  132]
done with chain 1. naccept=102400 (0.341332)
per block:  [   99 50001  1522    28 50001   754]
chi2 at max = 83.985856
Max ln likelihood -41.992928 at parameters:
[  0.65824847   2.          26.07631003   0.69312021   2.          38.8053892 ]
            \log A_1 mean = 0.573949 +- 0.0839839
                 T_1 mean = 30.1995 +- 3.65207
            \log A_2 mean = 0.6783 +- 0.0265781
                 T_2 mean = 38.4131 +- 0.843203
ln Pr of mean = -60.201872
chi2(mean) = 120.403744
Object[s] Mrk273(z=0.038)

100% |########################################################################|



done with chain 0. naccept=5121 (0.341377)

100% |########################################################################|
100% |########################################################################|



per block:  [  20 2501   25   11 2501   68]
done with chain 1. naccept=110776 (0.369252)
per block:  [ 1681 50001  5580   314 50001  3204]
chi2 at max = 414.416101
Max ln likelihood -207.208051 at parameters:
[  0.55889104   2.          25.54891725   0.58412844   2.          38.1288889 ]
            \log A_1 mean = 0.609009 +- 0.0762596
                 T_1 mean = 25.5841 +- 1.72663
            \log A_2 mean = 0.55216 +- 0.013673
                 T_2 mean = 38.6624 +- 0.531106
ln Pr of mean = -208.930900
chi2(mean) = 417.861800
Object[s] Mrk463(z=0.050)

100% |########################################################################|



done with chain 0. naccept=9181 (0.612026)

100% |########################################################################|
100% |########################################################################|



per block:  [2474 2501 1675    3 2501   32]
done with chain 1. naccept=222164 (0.740544)
per block:  [49933 50001 43116  2926 50001 26192]
chi2 at max = 36.300145
Max ln likelihood -18.150073 at parameters:
[ -1.27205176e+04   2.00000000e+00   3.71677232e+00  -2.83053759e-01
   2.00000000e+00   3.45462948e+01]
            \log A_1 mean = -12853.8 +- 7487.7
                 T_1 mean = 18.8093 +- 9.14747
            \log A_2 mean = -0.278073 +- 0.0547121
                 T_2 mean = 34.4314 +- 1.63256
ln Pr of mean = -18.262525
chi2(mean) = 36.525051
Object[s] Arp220(z=0.018)

100% |########################################################################|



done with chain 0. naccept=9750 (0.649957)

100% |########################################################################|
100% |########################################################################|
model.py:423: RuntimeWarning: overflow encountered in double_scalars
  self.A2 = 10.0**logA2



per block:  [   9 2501   26 2482 2501 2236]
done with chain 1. naccept=191034 (0.636778)
per block:  [  356 50001  1633 49965 50001 39083]
chi2 at max = 756.557919
Max ln likelihood -378.278960 at parameters:
[  1.98161528e+00   2.00000000e+00   2.62443937e+01  -1.51112706e+04
   2.00000000e+00   9.77262475e+01]
            \log A_1 mean = 1.97125 +- 0.0145092
                 T_1 mean = 26.5542 +- 0.442053
            \log A_2 mean = -15955.6 +- 6795.86
                 T_2 mean = 63.544 +- 21.1699
ln Pr of mean = -379.949655
chi2(mean) = 759.899309
Object[s] NGC6240(z=0.024)

100% |########################################################################|



done with chain 0. naccept=5069 (0.337911)

100% |########################################################################|
100% |########################################################################|



per block:  [  14 2501   24    7 2501   27]
done with chain 1. naccept=108362 (0.361205)
per block:  [ 3247 50001  2584  1321 50001  1213]
chi2 at max = 490.351610
Max ln likelihood -245.175805 at parameters:
[  1.29950146   2.          16.17873661   0.70169467   2.          36.95378181]
            \log A_1 mean = 1.14589 +- 0.0775266
                 T_1 mean = 21.0318 +- 2.62063
            \log A_2 mean = 0.531272 +- 0.0862176
                 T_2 mean = 39.0947 +- 1.08623
ln Pr of mean = -349.073463
chi2(mean) = 698.146926
One-Component
Object[s] IRAS00188-0856(z=0.128)


100% |########################################################################|


KeyboardInterrupt: 

In [2]:
#%%px --noblock
%run driver.py --format=DLC_2014 --fdir=./figs_DLC_2014_2 --odir=./out_DLC_2014_2 --file=./herus_phot.csv 0

/Volumes/Data/Users/jaffe/Library/Python/2.7/lib/python/site-packages/matplotlib-1.3.1-py2.7-macosx-10.6-intel.egg/matplotlib/__init__.py:1155: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


normal behaviour
filename: ./herus_phot.csv
fig dir: ./figs_DLC_2014_2/
out dir: ./out_DLC_2014_2/
data range None
DLC_UL = 1
format = 0
filetype = DLC_2014
which= [0]
Using file ./herus_phot.csv
keywords: {'random': True, 'randomrestart': True, 'filetype': 'DLC_2014', 'format': 0, 'DLC_ul': True}
Two-Component beta = 2
Object[s] IRAS00188-0856(z=0.128)
Number of prior resamples: 2
done with chain 0. naccept=5202 (0.346777)

100% |########################################################################|
100% |########################################################################|



per block:  [   8 2501   90   16 2501   91]
Number of prior resamples: 213
done with chain 1. naccept=200161 (0.667201)
per block:  [ 1468 50001  1070 49999 50001 47627]
chi2 at max = 23.960476
Max ln likelihood -11.980238 at parameters:
[   0.11958923    2.           31.6869833  -108.35336389    2.
   42.34247664]
            \log A_1 mean = 0.115103 +- 0.0432487
                 T_1 mean = 31.8705 +- 1.58634
            \log A_2 mean = -59.1526 +- 22.238
                 T_2 mean = 65.4563 +- 19.4743
ln Pr of mean = -12.250167
chi2(mean) = 24.500333
Object[s] IRAS00397-1312(z=0.262)

100% |########################################################################|



done with chain 0. naccept=8828 (0.588494)

100% |########################################################################|
100% |########################################################################|



per block:  [2300 2501 1499    9 2501   23]
done with chain 1. naccept=236271 (0.787567)
per block:  [49971 50001 44661 12544 50001 29098]
chi2 at max = 11.697852
Max ln likelihood -5.848926 at parameters:
[ -1.9356365    2.          34.72607573  -0.67132276   2.          42.47053231]
            \log A_1 mean = -11760 +- 5001.49
                 T_1 mean = 22.715 +- 11.3212
            \log A_2 mean = -0.643731 +- 0.0493647
                 T_2 mean = 41.9423 +- 1.5708
ln Pr of mean = -6.022750
chi2(mean) = 12.045499
Object[s] IRAS01003-2238(z=0.118)

100% |########################################################################|



done with chain 0. naccept=9503 (0.633491)

100% |########################################################################|
100% |########################################################################|



per block:  [2474 2501 1920   14 2501   98]
Number of prior resamples: 16
done with chain 1. naccept=206000 (0.686664)
per block:  [49806 50001 41807  5472 50001  8918]
chi2 at max = 2.705686
Max ln likelihood -1.352843 at parameters:
[ -2.00920507   2.          31.02827203  -0.80349325   2.          45.0750897 ]
            \log A_1 mean = -5067.89 +- 4584.43
                 T_1 mean = 23.6373 +- 12.0467
            \log A_2 mean = -0.787713 +- 0.0184037
                 T_2 mean = 44.8595 +- 0.828058
ln Pr of mean = -1.390887
chi2(mean) = 2.781773
Object[s] IRAS03158+4227(z=0.134)

100% |########################################################################|



Number of prior resamples: 7
done with chain 0. naccept=9811 (0.654023)

100% |########################################################################|
100% |########################################################################|



per block:  [  18 2501   27 2497 2501 2272]
done with chain 1. naccept=132461 (0.441535)
per block:  [  259 50001  3101 15056 50001 14048]
chi2 at max = 29.173054
Max ln likelihood -14.586527 at parameters:
[  0.27708598   2.          27.35767051  -1.5866489    2.          68.77885618]
            \log A_1 mean = 0.461361 +- 0.192033
                 T_1 mean = 24.0311 +- 2.88674
            \log A_2 mean = -484.486 +- 898.706
                 T_2 mean = 69.4807 +- 14.6528
ln Pr of mean = -125.142726
chi2(mean) = 250.285452
Object[s] IRAS03521+0028(z=0.152)

100% |########################################################################|



done with chain 0. naccept=5196 (0.346377)

100% |########################################################################|
100% |########################################################################|



per block:  [  14 2501  144    3 2501   38]
done with chain 1. naccept=159644 (0.532145)
per block:  [26443 50001 11772  5575 50001 15857]
chi2 at max = 0.021230
Max ln likelihood -0.010615 at parameters:
[  0.43393546   2.          11.64795548  -0.22480234   2.          38.07681331]
            \log A_1 mean = 0.454932 +- 0.280938
                 T_1 mean = 11.8827 +- 2.84225
            \log A_2 mean = -0.222166 +- 0.0380794
                 T_2 mean = 37.869 +- 0.913049
ln Pr of mean = -1.840032
chi2(mean) = 3.680065
Object[s] IRAS05189-2524(z=0.043)

100% |########################################################################|



Number of prior resamples: 5
done with chain 0. naccept=5069 (0.337911)

100% |########################################################################|
100% |########################################################################|



per block:  [  15 2501   30    7 2501   20]
done with chain 1. naccept=104837 (0.349456)
per block:  [  353 50001  3309   361 50001   817]
chi2 at max = 30.364782
Max ln likelihood -15.182391 at parameters:
[  0.51905197   2.          28.71931567  -0.40037455   2.          50.74844815]
            \log A_1 mean = 0.528433 +- 0.0531746
                 T_1 mean = 28.4128 +- 1.0239
            \log A_2 mean = -0.388282 +- 0.0123816
                 T_2 mean = 50.5869 +- 0.32503
ln Pr of mean = -16.089968
chi2(mean) = 32.179936
Object[s] IRAS06035-7102(z=0.079)

100% |########################################################################|



done with chain 0. naccept=9447 (0.629758)


100% |########################################################################|



per block:  [2440 2501 1960   15 2501   35]
done with chain 1. naccept=189883 (0.632941)
per block:  [49810 50001 39143   435 50001   498]
chi2 at max = 56.578722
Max ln likelihood -28.289361 at parameters:
[ -5.46509766e+03   2.00000000e+00   1.77059830e+01   1.47798881e-01
   2.00000000e+00   3.63324307e+01]
            \log A_1 mean = -5267.24 +- 3776.79
                 T_1 mean = 19.5924 +- 9.65681
            \log A_2 mean = 0.14781 +- 0.00352328
                 T_2 mean = 36.3341 +- 0.10284
ln Pr of mean = -28.285365
chi2(mean) = 56.570731
Object[s] IRAS06206-6315(z=0.092)

100% |########################################################################|



done with chain 0. naccept=9308 (0.620492)

100% |########################################################################|
100% |########################################################################|



per block:  [2487 2501 1796    5 2501   23]
done with chain 1. naccept=195525 (0.651748)
per block:  [49729 50001 41054   406 50001  4339]
chi2 at max = 100.857067
Max ln likelihood -50.428534 at parameters:
[ -1.47504222   2.          11.41587115   0.25874588   2.          33.43337096]
            \log A_1 mean = -4435.8 +- 3638.8
                 T_1 mean = 18.0485 +- 8.65214
            \log A_2 mean = 0.270922 +- 0.0383887
                 T_2 mean = 33.0403 +- 1.17325
ln Pr of mean = -53.301520
chi2(mean) = 106.603040
Object[s] IRAS07598+6508(z=0.148)

100% |########################################################################|



done with chain 0. naccept=8930 (0.595294)

100% |########################################################################|
100% |########################################################################|



per block:  [2465 2501 1427   13 2501   28]
done with chain 1. naccept=217252 (0.724171)
per block:  [49937 50001 44752  1278 50001 21288]
chi2 at max = 39.276845
Max ln likelihood -19.638423 at parameters:
[ -8.41062879e+03   2.00000000e+00   7.82479355e+00  -2.59699817e-01
   2.00000000e+00   3.56066778e+01]
            \log A_1 mean = -7915.7 +- 3594.3
                 T_1 mean = 18.6324 +- 9.34564
            \log A_2 mean = -0.226661 +- 0.125409
                 T_2 mean = 34.7447 +- 3.12435
ln Pr of mean = -26.457693
chi2(mean) = 52.915385
Object[s] IRAS08311-2459(z=0.100)

100% |########################################################################|



Number of prior resamples: 28
done with chain 0. naccept=5254 (0.350243)

100% |########################################################################|
100% |########################################################################|



per block:  [  22 2501  108   16 2501  111]
done with chain 1. naccept=103631 (0.345436)
per block:  [  396 50001   856   899 50001  1483]
chi2 at max = 2.571217
Max ln likelihood -1.285608 at parameters:
[  0.1499183    2.          25.99944821  -0.15839177   2.          39.61186553]
            \log A_1 mean = 0.108206 +- 0.0409967
                 T_1 mean = 30.4994 +- 3.0882
            \log A_2 mean = -0.276059 +- 0.0792624
                 T_2 mean = 38.5622 +- 1.81351
ln Pr of mean = -7.747469
chi2(mean) = 15.494938
Object[s] IRAS08572+3915(z=0.058)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=9583 (0.638824)

100% |########################################################################|
100% |########################################################################|
model.py:418: RuntimeWarning: overflow encountered in double_scalars
  self.A1 = 10.0**logA1
/Volumes/Data/Users/jaffe/home/proj/stats/MCMC/GaussianData.py:47: RuntimeWarning: overflow encountered in true_divide
  return dot(A.transpose()/self.sig2,A)



per block:  [2465 2501 2077   16 2501   28]
done with chain 1. naccept=191052 (0.636838)
per block:  [49811 50001 39175   636 50001  1433]
chi2 at max = 20.223359
Max ln likelihood -10.111679 at parameters:
[  0.95227577   2.           4.59825771  -0.37998152   2.          46.37031234]
            \log A_1 mean = -12436.2 +- 8672.96
                 T_1 mean = 24.9921 +- 12.5648
            \log A_2 mean = -0.37989 +- 0.00986489
                 T_2 mean = 46.393 +- 0.214217
ln Pr of mean = -10.836421
chi2(mean) = 21.672841
Object[s] IRAS09022-3615(z=0.060)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=5199 (0.346577)

100% |########################################################################|
100% |########################################################################|



per block:  [  20 2501   35   42 2501  105]
Number of prior resamples: 31
done with chain 1. naccept=104227 (0.347422)
per block:  [  394 50001  1268   236 50001  2332]
chi2 at max = 202.047225
Max ln likelihood -101.023613 at parameters:
[  0.53651075   2.          34.14663609  -1.1938622    2.          57.39295572]
            \log A_1 mean = 0.59854 +- 0.114227
                 T_1 mean = 32.0796 +- 2.83366
            \log A_2 mean = -1.19842 +- 0.0592824
                 T_2 mean = 64.5536 +- 7.05141
ln Pr of mean = -180.531140
chi2(mean) = 361.062279
Object[s] IRAS10378+1109(z=0.136)

100% |########################################################################|



done with chain 0. naccept=5266 (0.351043)

100% |########################################################################|
100% |########################################################################|



per block:  [  24 2501  104    9 2501  132]
done with chain 1. naccept=128616 (0.428719)
per block:  [  564 50001  3378  7990 50001 16687]
chi2 at max = 25.875357
Max ln likelihood -12.937679 at parameters:
[ -0.14909153   2.          29.77090632  -1.59830701   2.          61.12778208]
            \log A_1 mean = -0.160592 +- 0.0765687
                 T_1 mean = 28.4556 +- 1.27108
            \log A_2 mean = -1.30884 +- 0.321469
                 T_2 mean = 54.8643 +- 7.36883
ln Pr of mean = -23.260156
chi2(mean) = 46.520313
Object[s] IRAS10565+2448(z=0.043)

100% |########################################################################|



Number of prior resamples: 62
done with chain 0. naccept=5089 (0.339244)

100% |########################################################################|
100% |########################################################################|



per block:  [   8 2501   18    4 2501   62]
done with chain 1. naccept=104222 (0.347406)
per block:  [  243 50001  1187   664 50001  2131]
chi2 at max = 184.729639
Max ln likelihood -92.364820 at parameters:
[  0.88584634   2.          29.2266394   -1.52548586   2.          85.11526984]
            \log A_1 mean = 0.887068 +- 0.00365483
                 T_1 mean = 29.2204 +- 0.0830323
            \log A_2 mean = -1.57467 +- 0.0281663
                 T_2 mean = 88.3468 +- 2.08331
ln Pr of mean = -97.801626
chi2(mean) = 195.603252
Object[s] IRAS11095-0238(z=0.107)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=9354 (0.623558)

100% |########################################################################|
100% |########################################################################|



per block:  [2422 2501 1883    9 2501   43]
done with chain 1. naccept=206442 (0.688138)
per block:  [49835 50001 42727  2850 50001 11033]
chi2 at max = 11.007701
Max ln likelihood -5.503851 at parameters:
[ -9.61568051e+03   2.00000000e+00   3.96510675e+01  -4.96460894e-01
   2.00000000e+00   4.24675913e+01]
            \log A_1 mean = -8186.77 +- 5740.52
                 T_1 mean = 22.46 +- 11.4032
            \log A_2 mean = -0.494028 +- 0.0215055
                 T_2 mean = 42.369 +- 0.885379
ln Pr of mean = -5.533467
chi2(mean) = 11.066934
Object[s] IRAS12071-0444(z=0.128)

100% |########################################################################|



done with chain 0. naccept=7080 (0.471969)

100% |########################################################################|
100% |########################################################################|



per block:  [ 955 2501 1036   10 2501   82]
done with chain 1. naccept=196138 (0.653791)
per block:  [49896 50001 38965  4140 50001  3140]
chi2 at max = 7.327153
Max ln likelihood -3.663576 at parameters:
[ -3.98657590e+03   2.00000000e+00   1.43619327e+01  -3.45898012e-01
   2.00000000e+00   3.86925555e+01]
            \log A_1 mean = -5754.42 +- 2523.24
                 T_1 mean = 20.7232 +- 10.3754
            \log A_2 mean = -0.346727 +- 0.0115518
                 T_2 mean = 38.7295 +- 0.465999
ln Pr of mean = -3.666913
chi2(mean) = 7.333825
Object[s] IRAS13120-5453(z=0.031)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=8979 (0.598560)

100% |########################################################################|
100% |########################################################################|



per block:  [2475 2501 1454   16 2501   37]
done with chain 1. naccept=103357 (0.344522)
per block:  [ 1015 50001  2137   118 50001    90]
chi2 at max = 2194.726861
Max ln likelihood -1097.363431 at parameters:
[  1.02515624   2.          19.61599997   1.23216933   2.          33.66774594]
            \log A_1 mean = -14.2369 +- 124.527
                 T_1 mean = 19.3816 +- 1.82687
            \log A_2 mean = 1.26394 +- 0.0325888
                 T_2 mean = 33.3335 +- 0.353174
ln Pr of mean = -4133.412329
chi2(mean) = 8266.824657
Object[s] IRAS13451+1232(z=0.122)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=6144 (0.409573)

100% |########################################################################|
100% |########################################################################|



per block:  [  15 2501   18  414 2501  700]
done with chain 1. naccept=201073 (0.670241)
per block:  [  891 50001  6530 49989 50001 43666]
chi2 at max = 456.284302
Max ln likelihood -228.142151 at parameters:
[  7.08545867e-01   2.00000000e+00   1.68166186e+01  -9.08004490e+03
   2.00000000e+00   3.35102064e+01]
            \log A_1 mean = 0.738995 +- 0.0422619
                 T_1 mean = 16.5061 +- 0.411621
            \log A_2 mean = -4194.24 +- 2918.93
                 T_2 mean = 57.8748 +- 23.9668
ln Pr of mean = -228.803286
chi2(mean) = 457.606573
Object[s] IRAS14348-1447(z=0.083)

100% |########################################################################|



done with chain 0. naccept=9673 (0.644824)

100% |########################################################################|
100% |########################################################################|



per block:  [2468 2501 2155   14 2501   39]
done with chain 1. naccept=190514 (0.635045)
per block:  [49744 50001 40364   193 50001   216]
chi2 at max = 105233.519554
Max ln likelihood -52616.759777 at parameters:
[ -1.68071825e+04   2.00000000e+00   3.51599146e+01   1.10790897e-01
   2.00000000e+00   5.73408537e+01]
            \log A_1 mean = -7212.25 +- 5517.65
                 T_1 mean = 29.97 +- 15.4953
            \log A_2 mean = 0.125319 +- 0.0294115
                 T_2 mean = 56.9189 +- 0.812226
ln Pr of mean = -52690.783373
chi2(mean) = 105381.566747
Object[s] IRAS14378-3651(z=0.068)

100% |########################################################################|



done with chain 0. naccept=5071 (0.338044)

100% |########################################################################|
100% |########################################################################|



per block:  [  11 2501   34    6 2501   23]
done with chain 1. naccept=116916 (0.389719)
per block:  [  618 50001 10860  2400 50001  3041]
chi2 at max = 3.478932
Max ln likelihood -1.739466 at parameters:
[  0.06917808   2.          29.3053816   -0.09318444   2.          40.11193434]
            \log A_1 mean = 0.0827473 +- 0.0876658
                 T_1 mean = 28.468 +- 2.80502
            \log A_2 mean = -0.073072 +- 0.0382347
                 T_2 mean = 39.8586 +- 0.311756
ln Pr of mean = -7.660560
chi2(mean) = 15.321119
Object[s] IRAS15250+3609(z=0.055)

100% |########################################################################|



done with chain 0. naccept=5157 (0.343777)

100% |########################################################################|
100% |########################################################################|



per block:  [  10 2501   10   15 2501  125]
done with chain 1. naccept=141502 (0.471672)
per block:  [ 3636 50001 32034  1705 50001  4130]
chi2 at max = 23.246784
Max ln likelihood -11.623392 at parameters:
[  0.38433835   2.          20.82285398  -0.36344026   2.          46.10089501]
            \log A_1 mean = 0.383734 +- 0.0652495
                 T_1 mean = 21.7499 +- 1.07575
            \log A_2 mean = -0.446406 +- 0.0479371
                 T_2 mean = 47.8105 +- 1.1932
ln Pr of mean = -12.350773
chi2(mean) = 24.701547
Object[s] IRAS15462-0450(z=0.100)

100% |########################################################################|



Number of prior resamples: 7
done with chain 0. naccept=9453 (0.630158)

100% |########################################################################|
100% |########################################################################|



per block:  [2478 2501 1920   10 2501   48]
Number of prior resamples: 16
done with chain 1. naccept=203040 (0.676798)
per block:  [49928 50001 40135  1801 50001 11179]
chi2 at max = 11.799758
Max ln likelihood -5.899879 at parameters:
[ -7.84819528e+03   2.00000000e+00   2.40548600e+01  -2.56035717e-01
   2.00000000e+00   3.69940351e+01]
            \log A_1 mean = -4747.55 +- 2912.97
                 T_1 mean = 20.0393 +- 9.83236
            \log A_2 mean = -0.255625 +- 0.0146203
                 T_2 mean = 36.9716 +- 0.535937
ln Pr of mean = -5.900332
chi2(mean) = 11.800665
Object[s] IRAS16090-0139(z=0.134)

100% |########################################################################|



done with chain 0. naccept=9239 (0.615892)

100% |########################################################################|
100% |########################################################################|



per block:  [2461 2501 1760    6 2501   15]
Number of prior resamples: 34
done with chain 1. naccept=210382 (0.701271)
per block:  [49960 50001 42524   928 50001 16973]
chi2 at max = 29.506190
Max ln likelihood -14.753095 at parameters:
[ -1.15945923e+04   2.00000000e+00   2.17003154e+01   8.66077240e-02
   2.00000000e+00   3.55186933e+01]
            \log A_1 mean = -11437.4 +- 7143.7
                 T_1 mean = 18.9668 +- 9.34392
            \log A_2 mean = 0.0948468 +- 0.0394077
                 T_2 mean = 35.2531 +- 1.26494
ln Pr of mean = -15.467704
chi2(mean) = 30.935408
Object[s] IRAS17208-0014(z=0.043)

100% |########################################################################|



done with chain 0. naccept=5079 (0.338577)

100% |########################################################################|
100% |########################################################################|



per block:  [  10 2501   17    6 2501   49]
done with chain 1. naccept=105160 (0.350532)
per block:  [  792 50001  2095  1011 50001  1265]
chi2 at max = 84.832675
Max ln likelihood -42.416338 at parameters:
[  1.21375621   2.          29.58046068  -0.79270478   2.          70.85611966]
            \log A_1 mean = 1.21606 +- 0.0355066
                 T_1 mean = 29.6216 +- 0.942075
            \log A_2 mean = -0.90225 +- 0.0516503
                 T_2 mean = 75.8008 +- 4.03969
ln Pr of mean = -59.205147
chi2(mean) = 118.410295
Object[s] IRAS19254-7245(z=0.062)

100% |########################################################################|



Number of prior resamples: 2
done with chain 0. naccept=8484 (0.565562)

100% |########################################################################|
100% |########################################################################|



per block:  [2493 2501  957   15 2501   22]
done with chain 1. naccept=197100 (0.656998)
per block:  [48756 50001 45916   598 50001  1833]
chi2 at max = 299.303972
Max ln likelihood -149.651986 at parameters:
[  0.47577678   2.          11.17652719   0.36376429   2.          33.71692739]
            \log A_1 mean = -6499.59 +- 4182.72
                 T_1 mean = 17.8441 +- 8.78584
            \log A_2 mean = 0.39824 +- 0.120756
                 T_2 mean = 33.2133 +- 2.34391
ln Pr of mean = -224.540664
chi2(mean) = 449.081327
Object[s] IRAS19297-0406(z=0.086)

100% |########################################################################|



done with chain 0. naccept=8740 (0.582628)

100% |########################################################################|
100% |########################################################################|



per block:  [2483 2501 1203   24 2501   33]
done with chain 1. naccept=168193 (0.560641)
per block:  [33755 50001 32442   408 50001  1591]
chi2 at max = 30.797946
Max ln likelihood -15.398973 at parameters:
[  0.31093435   2.          14.17369295   0.40809649   2.          35.0953363 ]
            \log A_1 mean = -2081.28 +- 2030.51
                 T_1 mean = 15.8633 +- 7.76393
            \log A_2 mean = 0.475216 +- 0.154371
                 T_2 mean = 33.7966 +- 3.46154
ln Pr of mean = -92.511531
chi2(mean) = 185.023062
Object[s] IRAS20087-0308(z=0.106)

100% |########################################################################|



done with chain 0. naccept=8528 (0.568495)

100% |########################################################################|
100% |########################################################################|



per block:  [2384 2501 1116    9 2501   22]
done with chain 1. naccept=199215 (0.664048)
per block:  [49781 50001 45379   889 50001  3169]
chi2 at max = 32.109311
Max ln likelihood -16.054655 at parameters:
[ -0.34372997   2.          11.50285886   0.45202811   2.          31.69254465]
            \log A_1 mean = -1119.23 +- 760.53
                 T_1 mean = 17.1565 +- 8.26324
            \log A_2 mean = 0.487519 +- 0.103952
                 T_2 mean = 30.8567 +- 2.47545
ln Pr of mean = -41.481311
chi2(mean) = 82.962621
Object[s] IRAS20100-4156(z=0.130)

100% |########################################################################|



done with chain 0. naccept=5179 (0.345244)

100% |########################################################################|
100% |########################################################################|



per block:  [  27 2501   31   37 2501   87]
done with chain 1. naccept=106388 (0.354625)
per block:  [  784 50001  4651   268 50001   688]
chi2 at max = 11.832764
Max ln likelihood -5.916382 at parameters:
[ -0.14349234   2.          33.04722707  -0.45566818   2.          43.63695133]
            \log A_1 mean = -0.115797 +- 0.134719
                 T_1 mean = 31.1907 +- 3.3792
            \log A_2 mean = -0.407521 +- 0.0363988
                 T_2 mean = 43.348 +- 0.322752
ln Pr of mean = -14.892021
chi2(mean) = 29.784042
Object[s] IRAS20414-1651(z=0.871)

100% |########################################################################|



done with chain 0. naccept=9012 (0.600760)

100% |########################################################################|
100% |########################################################################|
model.py:346: RuntimeWarning: invalid value encountered in multiply
  return self.A1 * greybody(self.b1, self.T1, data.freq) + \



per block:  [2473 2501 1485   17 2501   40]
done with chain 1. naccept=198139 (0.660461)
per block:  [49881 49987 45515   447 49987  2327]
chi2 at max = 101.727335
Max ln likelihood -50.863667 at parameters:
[  3.85997164   2.           3.99204502  -0.81776339   2.          53.35625022]
            \log A_1 mean = -22790.8 +- 13233.9
                 T_1 mean = 24.8516 +- 13.0292
            \log A_2 mean = -0.660016 +- 0.163246
                 T_2 mean = 46.5677 +- 5.80864
ln Pr of mean = -183.073865
chi2(mean) = 366.147729
Object[s] IRAS20551-4250(z=0.043)
Number of prior resamples: 66920793

100% |########################################################################|



done with chain 0. naccept=14413 (0.960803)

100% |########################################################################|
100% |########################################################################|



per block:  [2501 2501 2194 2501 2501 2220]
done with chain 1. naccept=270536 (0.901784)
per block:  [50001 50001 36428 50001 50001 34109]
chi2 at max = 288100.292392
Max ln likelihood -144050.146196 at parameters:
[ -1.77075745e+04   2.00000000e+00   9.95222803e+00  -7.75763967e+04
   2.00000000e+00   7.09575007e+01]
            \log A_1 mean = -23758.9 +- 3584.59
                 T_1 mean = 34.9297 +- 22.7496
            \log A_2 mean = -65937.4 +- 10857.2
                 T_2 mean = 67.3392 +- 22.8166
ln Pr of mean = -144050.146196
chi2(mean) = 288100.292392
Object[s] IRAS22491-1808(z=0.078)


100% |########################################################################|


KeyboardInterrupt: 

In [ ]:
#%%px --noblock
%run driver.py --format=DLC_2014 --fdir=./figs_DLC_2014_2 --odir=./out_DLC_2014_2 --file=./herus_phot.csv 1

In [ ]:
#%%px --noblock
%run driver.py --format=DLC_2014 --fdir=./figs_DLC_2014_2 --odir=./out_DLC_2014_2 --file=./herus_phot.csv 2

In [ ]:
#%%px --noblock
%run driver.py --format=DLC_2014 --fdir=./figs_DLC_2014_2 --odir=./out_DLC_2014_2 --file=./herus_phot.csv 3

In [6]:
reload(driver)
ret123 = driver.writeTabAll([], fbase="DLC_2015", dirname="./DLC_2015/out_DLC_2015_1/", nodat=True, check=True)

./DLC_2015/out_DLC_2015_1/check0.npy
nobj, npar, ndat =  43 4 0
./DLC_2015/out_DLC_2015_1/check1.npy
nobj, npar, ndat =  43 3 0
./DLC_2015/out_DLC_2015_1/check2.npy
nobj, npar, ndat =  43 2 0
./DLC_2015/out_DLC_2015_1/check3.npy
nobj, npar, ndat =  43 6 0
./DLC_2015/out_DLC_2015_1/check4.npy
nobj, npar, ndat =  43 4 0
nn, npar, ndat, nt =  43 4 0 2
nn, npar, ndat, nt =  43 3 0 1
nn, npar, ndat, nt =  43 2 0 1
nn, npar, ndat, nt =  43 6 0 2
nn, npar, ndat, nt =  43 4 0 1
